### ISSUE TITLE
A question about dataset

### ISSUE THREAD

**Issue by czifan** [yijingru/CRNCIS-Pytorch#1]
Hello! Thanks for sharing your good job, it is very helpful for me!

I have read your paper "CONTEXT-REFINED NEURAL CELL INSTANCE SEGMENTATION" and you explained "We use the same neural cell dataset as PNCIS [2]" in it. So I read the paper "PIXEL-WISE NEURAL CELL INSTANCE SEGMENTATION", but the author just mentioned that "The neural cell images used in our experiment came from a series of time-lapse microscopy videos". I can't find where to get this data set, could you please provide it to me?

Thanks so much~

**Comment by yijingru** [comment]
Sorry that I just saw this comment. The neural dataset is confidential but you can try the public dataset like Kaggle and plant phenotype. The kaggle list is released here https://github.com/yijingru/ANCIS-Pytorch.

**Comment by czifan** [comment]
Thank you for your help!
